<?php
/**
 * XAMPP Root Index
 * Generated by xampp-tools
 * Lists all configured virtual hosts and provides quick access
 */

// Load configuration
$vhosts_file = '{{XAMPP_ROOT_DIR}}\\..\\xampp-tools\\config\\vhosts.json';
$vhosts = [];

if (file_exists($vhosts_file)) {
    $vhosts_data = json_decode(file_get_contents($vhosts_file), true);
    if (isset($vhosts_data['vhosts'])) {
        $vhosts = $vhosts_data['vhosts'];
    }
}

// Determine VHOSTS_EXTENSION (default to .local)
$vhosts_ext = '.local';

// Get server info
$server_name = $_SERVER['SERVER_NAME'] ?? 'localhost';
$server_port = $_SERVER['SERVER_PORT'] ?? '80';
$protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
$base_url = "{$protocol}://{$server_name}";

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>XAMPP - Welcome</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            padding: 40px 20px;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
        }
        .header {
            text-align: center;
            color: white;
            margin-bottom: 40px;
        }
        .header h1 {
            font-size: 48px;
            margin-bottom: 10px;
        }
        .header p {
            font-size: 18px;
            opacity: 0.9;
        }
        .cards-container {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 20px;
            margin-bottom: 40px;
        }
        .card {
            background: white;
            border-radius: 8px;
            padding: 24px;
            box-shadow: 0 10px 40px rgba(0, 0, 0, 0.1);
            transition: transform 0.3s ease, box-shadow 0.3s ease;
        }
        .card:hover {
            transform: translateY(-5px);
            box-shadow: 0 15px 50px rgba(0, 0, 0, 0.2);
        }
        .card h2 {
            color: #333;
            margin-bottom: 12px;
            font-size: 20px;
        }
        .card p {
            color: #666;
            margin-bottom: 16px;
            line-height: 1.6;
        }
        .btn {
            display: inline-block;
            padding: 10px 20px;
            background: #667eea;
            color: white;
            text-decoration: none;
            border-radius: 4px;
            transition: background 0.3s ease;
        }
        .btn:hover {
            background: #764ba2;
        }
        .vhosts-list {
            background: white;
            border-radius: 8px;
            padding: 24px;
            box-shadow: 0 10px 40px rgba(0, 0, 0, 0.1);
        }
        .vhosts-list h2 {
            color: #333;
            margin-bottom: 20px;
            font-size: 24px;
            border-bottom: 2px solid #667eea;
            padding-bottom: 12px;
        }
        .vhost-item {
            padding: 12px 0;
            border-bottom: 1px solid #eee;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .vhost-item:last-child {
            border-bottom: none;
        }
        .vhost-name {
            font-weight: 500;
            color: #333;
        }
        .vhost-link {
            color: #667eea;
            text-decoration: none;
            margin-left: 12px;
        }
        .vhost-link:hover {
            text-decoration: underline;
        }
        .tools-container {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
            margin-top: 40px;
        }
        .info-text {
            color: #666;
            font-size: 14px;
            margin-top: 8px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🚀 XAMPP</h1>
            <p>Local Development Environment</p>
        </div>

        <div class="cards-container">
            <div class="card">
                <h2>📊 Server Info</h2>
                <p>
                    <strong>Server Name:</strong> <?php echo htmlspecialchars($server_name); ?><br>
                    <strong>Port:</strong> <?php echo htmlspecialchars($server_port); ?><br>
                    <strong>Protocol:</strong> <?php echo htmlspecialchars($protocol); ?>
                </p>
            </div>

            <div class="card">
                <h2>⚙️ Tools</h2>
                <p>Access useful development tools:</p>
                <a href="http://localhost/phpmyadmin" class="btn">phpMyAdmin</a>
                <p style="margin-top: 12px;">
                    <a href="<?php echo htmlspecialchars(strtolower($protocol === 'https' ? $base_url : 'http://localhost')); ?>/info.php" class="btn" style="background: #764ba2;">PHP Info</a>
                </p>
            </div>

            <div class="card">
                <h2>📁 Document Root</h2>
                <p>
                    <strong>Path:</strong><br>
                    <code style="background: #f5f5f5; padding: 4px 8px; border-radius: 3px;">{{XAMPP_DOCUMENT_ROOT}}</code>
                </p>
                <p class="info-text">Your website files should be placed here.</p>
            </div>
        </div>

        <?php if (!empty($vhosts)): ?>
        <div class="vhosts-list">
            <h2>🌐 Virtual Hosts</h2>
            <?php foreach ($vhosts as $vhost): ?>
                <div class="vhost-item">
                    <span class="vhost-name"><?php echo htmlspecialchars($vhost['name'] ?? 'Unnamed'); ?></span>
                    <?php 
                        $vhost_name = $vhost['serverName'] ?? ($vhost['folder'] . $vhosts_ext);
                        $vhost_url = "http://" . htmlspecialchars($vhost_name);
                    ?>
                    <a href="<?php echo $vhost_url; ?>" class="vhost-link" target="_blank">Visit →</a>
                </div>
            <?php endforeach; ?>
        </div>
        <?php endif; ?>
    </div>
</body>
</html>
