<?php
/**
 * PHP Information Page
 * Generated by xampp-tools
 * Displays phpinfo() output
 */

// Add a simple title section before phpinfo()
?>
<!DOCTYPE html>
<html>
<head>
    <title>PHP Information</title>
    <style>
        body { 
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            margin: 0;
            padding: 20px;
            background: #f5f5f5;
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 20px;
            text-align: center;
        }
        .header h1 {
            margin: 0;
            font-size: 28px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>ℹ️ PHP Information</h1>
        <p>PHP Version: <?php echo phpversion(); ?></p>
    </div>

<?php
    phpinfo();
?>
</body>
</html>
